package retrieval

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"math"
	"net"
	"path"
	"regexp"
	"sort"
	"strings"

	qdrant "github.com/qdrant/go-client/qdrant"

	"github.com/rvbernucci/forja-guide/internal/contracts"
)

const (
	DenseVectorName  = "dense"
	SparseVectorName = "sparse"
)

var qdrantCollectionNamePattern = regexp.MustCompile(`^[a-z][a-z0-9_-]{0,119}$`)

// QdrantCollectionPlan is a fully specified, versioned derived-index build.
// The database records the same generation before this plan is applied.
type QdrantCollectionPlan struct {
	Create       *qdrant.CreateCollection
	PayloadIndex []*qdrant.CreateFieldIndexCollection
}

// QdrantUpsertClient is the narrow portion of the official client used by the
// projection worker. Keeping the transport boundary narrow makes idempotent
// worker behavior testable without treating a derived-store acknowledgement as
// canonical authority.
type QdrantUpsertClient interface {
	Upsert(context.Context, *qdrant.UpsertPoints) (*qdrant.UpdateResult, error)
}

type QdrantDeleteClient interface {
	Delete(context.Context, *qdrant.DeletePoints) (*qdrant.UpdateResult, error)
}

// PointWriter persists one validated derived point. Implementations must be
// idempotent for the stable point ID generated by BuildPoint.
type PointWriter interface {
	UpsertPoint(context.Context, contracts.RetrievalPoint) error
}

// PointDeleter removes derived points after the canonical store has already
// tombstoned their authority. It accepts stable IDs, not vector-store UUIDs.
type PointDeleter interface {
	DeletePoints(context.Context, []string) error
}

// QdrantPointWriter adapts the version-pinned official client to PointWriter.
// Wait=true is intentional: a projector cannot advance its PostgreSQL
// checkpoint before the derived write is acknowledged by Qdrant.
type QdrantPointWriter struct {
	Client         QdrantUpsertClient
	CollectionName string
}

// QdrantCollectionClient is the lifecycle subset of the official client. The
// operator is intentionally separate from the projector so collection changes
// remain explicit, operator-authorized actions rather than worker side effects.
type QdrantCollectionClient interface {
	CollectionExists(context.Context, string) (bool, error)
	CreateCollection(context.Context, *qdrant.CreateCollection) error
	CreateFieldIndex(context.Context, *qdrant.CreateFieldIndexCollection) (*qdrant.UpdateResult, error)
	GetCollectionInfo(context.Context, string) (*qdrant.CollectionInfo, error)
}

// QdrantAliasClient applies Qdrant's atomic alias operation set. A caller must
// verify the green collection before choosing to switch the stable alias.
type QdrantAliasClient interface {
	UpdateAliases(context.Context, []*qdrant.AliasOperations) error
	ListAliases(context.Context) ([]*qdrant.AliasDescription, error)
}

// QdrantAliasInspector reads the current alias map from Qdrant. Alias names
// are mutable routing pointers, so a successful UpdateAliases acknowledgement
// alone is not evidence that the intended physical generation is serving.
type QdrantAliasInspector interface {
	ListAliases(context.Context) ([]*qdrant.AliasDescription, error)
}

// QdrantBlueGreenClient is the intentionally small client surface needed for
// a guarded collection cutover. It is separate from projection and query
// clients: creating or switching a collection remains an explicit operator
// action rather than an automatic worker side effect.
type QdrantBlueGreenClient interface {
	QdrantCollectionClient
	QdrantAliasClient
	QdrantAliasInspector
}

// AliasObservation is the bounded, non-content evidence of one alias lookup.
// Exists distinguishes an absent alias during first activation from a failed
// lookup; callers must never treat an inspection error as an absent alias.
type AliasObservation struct {
	AliasName      string
	CollectionName string
	Exists         bool
}

// EnsureQdrantCollection creates the physical collection if absent and ensures
// the mandatory payload indexes before any projector is permitted to ingest
// points. It does not switch a serving alias or silently alter an existing
// collection's vector contract.
func EnsureQdrantCollection(ctx context.Context, client QdrantCollectionClient, plan QdrantCollectionPlan) error {
	if client == nil || plan.Create == nil || !qdrantCollectionNamePattern.MatchString(plan.Create.CollectionName) {
		return fmt.Errorf("Qdrant collection plan is invalid")
	}
	exists, err := client.CollectionExists(ctx, plan.Create.CollectionName)
	if err != nil {
		return fmt.Errorf("check Qdrant collection: %w", err)
	}
	if !exists {
		if err := client.CreateCollection(ctx, plan.Create); err != nil {
			return fmt.Errorf("create Qdrant collection: %w", err)
		}
	}
	for _, index := range plan.PayloadIndex {
		if index == nil || index.CollectionName != plan.Create.CollectionName || index.FieldName == "" {
			return fmt.Errorf("Qdrant payload index plan is invalid")
		}
		if _, err := client.CreateFieldIndex(ctx, index); err != nil {
			return fmt.Errorf("create Qdrant payload index %s: %w", index.FieldName, err)
		}
	}
	info, err := client.GetCollectionInfo(ctx, plan.Create.CollectionName)
	if err != nil {
		return fmt.Errorf("inspect Qdrant collection: %w", err)
	}
	return VerifyQdrantCollection(info, plan)
}

// VerifyQdrantCollection checks the live physical store against the immutable
// generation contract before a projector may acknowledge data into it. It does
// not trust an alias name, collection name, or operator intent as evidence of
// vector compatibility.
func VerifyQdrantCollection(info *qdrant.CollectionInfo, plan QdrantCollectionPlan) error {
	if info == nil || plan.Create == nil || !qdrantCollectionNamePattern.MatchString(plan.Create.CollectionName) {
		return fmt.Errorf("Qdrant collection verification input is invalid")
	}
	config := info.GetConfig()
	if config == nil || config.GetStrictModeConfig() == nil || !config.GetStrictModeConfig().GetEnabled() || config.GetStrictModeConfig().GetUnindexedFilteringRetrieve() || config.GetStrictModeConfig().GetUnindexedFilteringUpdate() {
		return fmt.Errorf("Qdrant strict filtering contract is not satisfied")
	}
	params := config.GetParams()
	if params == nil || params.GetVectorsConfig() == nil || params.GetVectorsConfig().GetParamsMap() == nil || params.GetSparseVectorsConfig() == nil || plan.Create.GetVectorsConfig() == nil || plan.Create.GetVectorsConfig().GetParamsMap() == nil {
		return fmt.Errorf("Qdrant vector configuration is incomplete")
	}
	expectedDense := plan.Create.GetVectorsConfig().GetParamsMap().GetMap()[DenseVectorName]
	actualDense := params.GetVectorsConfig().GetParamsMap().GetMap()[DenseVectorName]
	if expectedDense == nil || actualDense == nil || actualDense.GetSize() != expectedDense.GetSize() || actualDense.GetDistance() != expectedDense.GetDistance() {
		return fmt.Errorf("Qdrant dense vector contract is not satisfied")
	}
	if params.GetSparseVectorsConfig().GetMap()[SparseVectorName] == nil {
		return fmt.Errorf("Qdrant sparse vector contract is not satisfied")
	}
	metadata := config.GetMetadata()
	if metadata["forja_schema_version"].GetStringValue() != contracts.RetrievalSchemaVersion || metadata["collection_generation"].GetStringValue() != plan.Create.GetMetadata()["collection_generation"].GetStringValue() {
		return fmt.Errorf("Qdrant collection generation metadata is not satisfied")
	}
	for _, index := range plan.PayloadIndex {
		if _, found := info.GetPayloadSchema()[index.FieldName]; !found {
			return fmt.Errorf("Qdrant payload index %s is missing", index.FieldName)
		}
	}
	return nil
}

// SwitchQdrantAlias atomically directs one stable alias to a verified physical
// generation. Existing aliases require Qdrant's delete-then-create sequence in
// one UpdateAliases request; first activation needs only the create action.
func SwitchQdrantAlias(ctx context.Context, client QdrantAliasClient, aliasName, collectionName string, expected AliasObservation) error {
	if client == nil || !qdrantCollectionNamePattern.MatchString(aliasName) || !qdrantCollectionNamePattern.MatchString(collectionName) {
		return fmt.Errorf("Qdrant alias switch is invalid")
	}
	if expected.AliasName != aliasName || (expected.Exists && !qdrantCollectionNamePattern.MatchString(expected.CollectionName)) || (!expected.Exists && expected.CollectionName != "") {
		return fmt.Errorf("Qdrant alias switch expectation is invalid")
	}
	current, err := ObserveQdrantAlias(ctx, client, aliasName)
	if err != nil {
		return err
	}
	if current != expected {
		return fmt.Errorf("Qdrant alias changed before switch")
	}
	if current.Exists && current.CollectionName == collectionName {
		return nil
	}
	actions := []*qdrant.AliasOperations{qdrant.NewAliasCreate(aliasName, collectionName)}
	if current.Exists {
		actions = []*qdrant.AliasOperations{
			qdrant.NewAliasDelete(aliasName),
			qdrant.NewAliasCreate(aliasName, collectionName),
		}
	}
	if err := client.UpdateAliases(ctx, actions); err != nil {
		return fmt.Errorf("switch Qdrant alias: %w", err)
	}
	return nil
}

// ObserveQdrantAlias reads exactly one stable alias target. It rejects
// malformed or duplicate responses instead of picking an arbitrary target,
// because doing so could silently direct governed retrieval to the wrong
// physical generation.
func ObserveQdrantAlias(ctx context.Context, client QdrantAliasInspector, aliasName string) (AliasObservation, error) {
	if client == nil || !qdrantCollectionNamePattern.MatchString(aliasName) {
		return AliasObservation{}, fmt.Errorf("Qdrant alias observation is invalid")
	}
	aliases, err := client.ListAliases(ctx)
	if err != nil {
		return AliasObservation{}, fmt.Errorf("list Qdrant aliases: %w", err)
	}
	result := AliasObservation{AliasName: aliasName}
	for _, alias := range aliases {
		if alias == nil || alias.GetAliasName() != aliasName {
			continue
		}
		if result.Exists || !qdrantCollectionNamePattern.MatchString(alias.GetCollectionName()) {
			return AliasObservation{}, fmt.Errorf("Qdrant alias observation is ambiguous")
		}
		result.Exists = true
		result.CollectionName = alias.GetCollectionName()
	}
	return result, nil
}

// VerifyQdrantAlias requires a post-operation read to prove the serving alias
// points at the expected collection. No caller may infer success merely from
// the request it sent to Qdrant.
func VerifyQdrantAlias(ctx context.Context, client QdrantAliasInspector, aliasName, collectionName string) (AliasObservation, error) {
	if !qdrantCollectionNamePattern.MatchString(collectionName) {
		return AliasObservation{}, fmt.Errorf("Qdrant alias target is invalid")
	}
	observation, err := ObserveQdrantAlias(ctx, client, aliasName)
	if err != nil {
		return AliasObservation{}, err
	}
	if !observation.Exists || observation.CollectionName != collectionName {
		return AliasObservation{}, fmt.Errorf("Qdrant alias target does not match expected collection")
	}
	return observation, nil
}

// CutoverQdrantCollection verifies a green physical collection, records the
// prior alias target, switches once, and reads the target back. The returned
// observation is the rollback precondition; it contains no cards, vectors, or
// secret material. PostgreSQL generation state must be updated only after this
// function returns success.
func CutoverQdrantCollection(ctx context.Context, client QdrantBlueGreenClient, aliasName string, plan QdrantCollectionPlan) (AliasObservation, error) {
	if client == nil || plan.Create == nil || !qdrantCollectionNamePattern.MatchString(aliasName) {
		return AliasObservation{}, fmt.Errorf("Qdrant collection cutover is invalid")
	}
	if err := EnsureQdrantCollection(ctx, client, plan); err != nil {
		return AliasObservation{}, fmt.Errorf("verify green Qdrant collection: %w", err)
	}
	previous, err := ObserveQdrantAlias(ctx, client, aliasName)
	if err != nil {
		return AliasObservation{}, err
	}
	if previous.Exists && previous.CollectionName == plan.Create.CollectionName {
		return previous, nil
	}
	if err := SwitchQdrantAlias(ctx, client, aliasName, plan.Create.CollectionName, previous); err != nil {
		return AliasObservation{}, err
	}
	if _, err := VerifyQdrantAlias(ctx, client, aliasName, plan.Create.CollectionName); err != nil {
		return AliasObservation{}, fmt.Errorf("verify Qdrant alias after cutover: %w", err)
	}
	return previous, nil
}

// RollbackQdrantCollection restores a prior target only when the alias still
// points at the expected green collection. This compare-before-switch rule
// prevents one recovery run from overwriting a newer, independently verified
// cutover. The caller is responsible for keeping the old collection alive for
// the declared observation window.
func RollbackQdrantCollection(ctx context.Context, client QdrantBlueGreenClient, aliasName, expectedGreen, previousCollection string) error {
	if client == nil || !qdrantCollectionNamePattern.MatchString(aliasName) || !qdrantCollectionNamePattern.MatchString(expectedGreen) || !qdrantCollectionNamePattern.MatchString(previousCollection) || expectedGreen == previousCollection {
		return fmt.Errorf("Qdrant collection rollback is invalid")
	}
	current, err := VerifyQdrantAlias(ctx, client, aliasName, expectedGreen)
	if err != nil {
		return fmt.Errorf("verify Qdrant alias before rollback: %w", err)
	}
	if !current.Exists {
		return fmt.Errorf("Qdrant alias is absent before rollback")
	}
	if err := SwitchQdrantAlias(ctx, client, aliasName, previousCollection, current); err != nil {
		return err
	}
	_, err = VerifyQdrantAlias(ctx, client, aliasName, previousCollection)
	if err != nil {
		return fmt.Errorf("verify Qdrant alias after rollback: %w", err)
	}
	return nil
}

func (writer QdrantPointWriter) UpsertPoint(ctx context.Context, point contracts.RetrievalPoint) error {
	if writer.Client == nil || !qdrantCollectionNamePattern.MatchString(writer.CollectionName) {
		return fmt.Errorf("Qdrant point writer is not configured")
	}
	wire, err := QdrantPoint(point)
	if err != nil {
		return err
	}
	wait := true
	if _, err := writer.Client.Upsert(ctx, &qdrant.UpsertPoints{
		CollectionName: writer.CollectionName,
		Wait:           &wait,
		Points:         []*qdrant.PointStruct{wire},
	}); err != nil {
		return fmt.Errorf("upsert retrieval point: %w", err)
	}
	return nil
}

func (writer QdrantPointWriter) DeletePoints(ctx context.Context, pointIDs []string) error {
	client, ok := writer.Client.(QdrantDeleteClient)
	if !ok || !qdrantCollectionNamePattern.MatchString(writer.CollectionName) || len(pointIDs) == 0 || len(pointIDs) > 1000 {
		return fmt.Errorf("Qdrant point delete is not configured")
	}
	ids := make([]*qdrant.PointId, 0, len(pointIDs))
	for _, pointID := range pointIDs {
		if !contracts.IsRetrievalPointID(pointID) {
			return fmt.Errorf("Qdrant point delete ID is invalid")
		}
		ids = append(ids, qdrant.NewID(pointUUID(pointID)))
	}
	wait := true
	if _, err := client.Delete(ctx, &qdrant.DeletePoints{
		CollectionName: writer.CollectionName, Wait: &wait, Points: qdrant.NewPointsSelectorIDs(ids),
	}); err != nil {
		return fmt.Errorf("delete retrieval points: %w", err)
	}
	return nil
}

// QdrantEndpoint is operator-supplied transport configuration. APIKey belongs
// in a secret boundary (environment or secret manager), never in a card,
// request contract, log line, or command argument.
type QdrantEndpoint struct {
	Host   string
	Port   int
	APIKey string
	UseTLS bool
}

// ClientConfig converts a validated endpoint to the official Qdrant Go client
// configuration. Non-loopback deployments require both TLS and an API key.
func (endpoint QdrantEndpoint) ClientConfig() (*qdrant.Config, error) {
	host := strings.TrimSpace(endpoint.Host)
	if host == "" || len(host) > 253 || endpoint.Port < 1 || endpoint.Port > 65535 {
		return nil, fmt.Errorf("Qdrant endpoint is invalid")
	}
	if !loopbackHost(host) && (!endpoint.UseTLS || strings.TrimSpace(endpoint.APIKey) == "") {
		return nil, fmt.Errorf("non-loopback Qdrant endpoint requires TLS and an API key")
	}
	return &qdrant.Config{
		Host: host, Port: endpoint.Port, APIKey: endpoint.APIKey, UseTLS: endpoint.UseTLS,
		PoolSize: 1, SkipCompatibilityCheck: false,
	}, nil
}

// OpenQdrant uses the official, version-pinned client after endpoint policy is
// validated. Callers retain ownership of Close and must bound every request.
func OpenQdrant(endpoint QdrantEndpoint) (*qdrant.Client, error) {
	config, err := endpoint.ClientConfig()
	if err != nil {
		return nil, err
	}
	client, err := qdrant.NewClient(config)
	if err != nil {
		return nil, fmt.Errorf("open Qdrant client: %w", err)
	}
	return client, nil
}

// BuildQdrantCollectionPlan produces a strict collection: every field used by
// governed retrieval filters has an explicit payload index before query traffic.
func BuildQdrantCollectionPlan(collectionName string, dimensions int, generation string) (QdrantCollectionPlan, error) {
	if !qdrantCollectionNamePattern.MatchString(collectionName) || dimensions < 1 || dimensions > 4096 || generation == "" {
		return QdrantCollectionPlan{}, fmt.Errorf("invalid Qdrant collection plan")
	}
	enabled := true
	disabled := false
	limit := uint32(200)
	conditionLimit := uint64(32)
	indexLimit := uint64(32)
	create := &qdrant.CreateCollection{
		CollectionName: collectionName,
		VectorsConfig: qdrant.NewVectorsConfigMap(map[string]*qdrant.VectorParams{
			DenseVectorName: {Size: uint64(dimensions), Distance: qdrant.Distance_Cosine},
		}),
		SparseVectorsConfig: qdrant.NewSparseVectorsConfig(map[string]*qdrant.SparseVectorParams{
			SparseVectorName: {},
		}),
		StrictModeConfig: &qdrant.StrictModeConfig{
			Enabled:                    &enabled,
			MaxQueryLimit:              &limit,
			UnindexedFilteringRetrieve: &disabled,
			UnindexedFilteringUpdate:   &disabled,
			FilterMaxConditions:        &conditionLimit,
			MaxPayloadIndexCount:       &indexLimit,
		},
		Metadata: qdrant.NewValueMap(map[string]any{
			"forja_schema_version":  contracts.RetrievalSchemaVersion,
			"collection_generation": generation,
		}),
	}
	wait := true
	keywordFields := []string{
		"tenant_id", "repository_id", "collection_generation", "entity_id", "artifact_family",
		"source_commit", "source_hash", "status", "authority_class", "language", "symbol_kind",
		"repository_path", "path_scope",
	}
	indexes := make([]*qdrant.CreateFieldIndexCollection, 0, len(keywordFields)+1)
	for _, field := range keywordFields {
		fieldType := qdrant.FieldType_FieldTypeKeyword
		indexes = append(indexes, &qdrant.CreateFieldIndexCollection{
			CollectionName: collectionName, FieldName: field, FieldType: &fieldType, Wait: &wait,
		})
	}
	boolType := qdrant.FieldType_FieldTypeBool
	indexes = append(indexes, &qdrant.CreateFieldIndexCollection{
		CollectionName: collectionName, FieldName: "stale", FieldType: &boolType, Wait: &wait,
	})
	return QdrantCollectionPlan{Create: create, PayloadIndex: indexes}, nil
}

// QdrantPoint converts a fully validated derived point into Qdrant's wire
// contract. The UUID is only an index key; the canonical stable PointID stays
// in payload and is checked again during canonical resolution.
func QdrantPoint(point contracts.RetrievalPoint) (*qdrant.PointStruct, error) {
	if err := contracts.ValidateRetrievalPoint(point); err != nil {
		return nil, fmt.Errorf("validate retrieval point: %w", err)
	}
	dense, err := float32Values(point.Dense)
	if err != nil {
		return nil, err
	}
	sparse, err := float32Values(point.Sparse.Values)
	if err != nil {
		return nil, err
	}
	payload, err := qdrant.TryValueMap(pointPayload(point))
	if err != nil {
		return nil, fmt.Errorf("encode Qdrant payload: %w", err)
	}
	return &qdrant.PointStruct{
		Id: qdrant.NewID(pointUUID(point.PointID)), Payload: payload,
		Vectors: qdrant.NewVectorsMap(map[string]*qdrant.Vector{
			DenseVectorName:  qdrant.NewVectorDense(dense),
			SparseVectorName: qdrant.NewVectorSparse(point.Sparse.Indices, sparse),
		}),
	}, nil
}

// BuildQdrantQueryRequest emits a bounded dense or sparse request with every
// access constraint embedded in the vector-store filter before ranking.
func BuildQdrantQueryRequest(
	collectionName string,
	query contracts.RetrievalQuery,
	dense []float64,
	sparse contracts.SparseVector,
	mode string,
) (*qdrant.QueryPoints, error) {
	if !qdrantCollectionNamePattern.MatchString(collectionName) {
		return nil, fmt.Errorf("invalid Qdrant collection name")
	}
	if err := contracts.ValidateRetrievalQuery(query); err != nil {
		return nil, err
	}
	filter, err := qdrantFilter(query)
	if err != nil {
		return nil, err
	}
	limit := query.Policy.DenseLimit
	using := DenseVectorName
	var rankQuery *qdrant.Query
	switch mode {
	case DenseVectorName:
		values, err := float32Values(dense)
		if err != nil || len(values) == 0 {
			return nil, fmt.Errorf("invalid dense retrieval query: %w", err)
		}
		rankQuery = qdrant.NewQueryDense(values)
	case SparseVectorName:
		values, err := float32Values(sparse.Values)
		if err != nil || len(values) == 0 || len(values) != len(sparse.Indices) {
			return nil, fmt.Errorf("invalid sparse retrieval query: %w", err)
		}
		if !strictAscending(sparse.Indices) {
			return nil, fmt.Errorf("sparse retrieval indices must be strictly ascending")
		}
		limit = query.Policy.SparseLimit
		using = SparseVectorName
		rankQuery = qdrant.NewQuerySparse(sparse.Indices, values)
	default:
		return nil, fmt.Errorf("unsupported retrieval mode %q", mode)
	}
	return &qdrant.QueryPoints{
		CollectionName: collectionName,
		Query:          rankQuery,
		Using:          &using,
		Filter:         filter,
		Limit:          qdrant.PtrOf(uint64(limit)),
		WithPayload: qdrant.NewWithPayloadInclude(
			"point_id", "entity_id", "artifact_family", "source_commit", "source_hash",
			"status", "authority_class", "stale", "language", "symbol_kind", "repository_path",
			"proof_refs", "collection_generation",
		),
	}, nil
}

func pointPayload(point contracts.RetrievalPoint) map[string]any {
	payload := map[string]any{
		"point_id": point.PointID, "entity_id": point.EntityID,
		"artifact_family": point.ArtifactFamily, "source_hash": point.SourceHash,
		"card_text_hash": point.CardTextHash, "status": point.Status,
		"authority_class": point.AuthorityClass, "stale": point.Stale,
		"tenant_id": point.TenantID, "repository_id": point.RepositoryID,
		"collection_generation": point.CollectionGeneration,
		"proof_refs":            stringInterfaces(point.ProofRefs),
		"path_scope":            stringInterfaces(pathScopes(point.RepositoryPath)),
	}
	if point.SourceCommit != nil {
		payload["source_commit"] = *point.SourceCommit
	}
	if point.Language != nil {
		payload["language"] = *point.Language
	}
	if point.SymbolKind != nil {
		payload["symbol_kind"] = *point.SymbolKind
	}
	if point.RepositoryPath != nil {
		payload["repository_path"] = *point.RepositoryPath
	}
	return payload
}

func qdrantFilter(query contracts.RetrievalQuery) (*qdrant.Filter, error) {
	must := []*qdrant.Condition{
		qdrant.NewMatchKeyword("tenant_id", query.TenantID),
		qdrant.NewMatchKeyword("repository_id", query.RepositoryID),
		qdrant.NewMatchKeyword("status", "active"),
		qdrant.NewMatchBool("stale", false),
		qdrant.NewMatchKeywords("artifact_family", query.Filters.ArtifactFamilies...),
		qdrant.NewMatchKeywords("authority_class", query.Filters.AuthorityClasses...),
		qdrant.NewMatchKeywords("path_scope", normalizeScopePaths(query.Scope.AllowedPaths)...),
	}
	if query.ExpectedGeneration != nil {
		must = append(must, qdrant.NewMatchKeyword("collection_generation", *query.ExpectedGeneration))
	}
	if len(query.Filters.Languages) > 0 {
		must = append(must, qdrant.NewMatchKeywords("language", query.Filters.Languages...))
	}
	if len(query.Filters.SymbolKinds) > 0 {
		must = append(must, qdrant.NewMatchKeywords("symbol_kind", query.Filters.SymbolKinds...))
	}
	filter := &qdrant.Filter{Must: must}
	sourceBound, repositoryGlobal := retrievalFamilyGroups(query.Filters.ArtifactFamilies)
	switch {
	case len(sourceBound) > 0 && len(repositoryGlobal) > 0:
		// Couple source-commit semantics to artifact family. This avoids a broad
		// source-commit OR that could return source-bound code from another commit.
		filter.Should = []*qdrant.Condition{
			qdrant.NewFilterAsCondition(&qdrant.Filter{Must: []*qdrant.Condition{
				qdrant.NewMatchKeywords("artifact_family", sourceBound...),
				qdrant.NewMatchKeyword("source_commit", query.Scope.SourceCommit),
			}}),
			qdrant.NewFilterAsCondition(&qdrant.Filter{Must: []*qdrant.Condition{
				qdrant.NewMatchKeywords("artifact_family", repositoryGlobal...),
				qdrant.NewIsNull("source_commit"),
			}}),
		}
	case len(sourceBound) > 0:
		filter.Must = append(filter.Must, qdrant.NewMatchKeyword("source_commit", query.Scope.SourceCommit))
	case len(repositoryGlobal) > 0:
		filter.Must = append(filter.Must, qdrant.NewIsNull("source_commit"))
	default:
		return nil, fmt.Errorf("retrieval query has no supported artifact families")
	}
	if len(query.Scope.DeniedPaths) > 0 {
		filter.MustNot = []*qdrant.Condition{
			qdrant.NewMatchKeywords("path_scope", normalizeScopePaths(query.Scope.DeniedPaths)...),
		}
	}
	return filter, nil
}

func retrievalFamilyGroups(families []string) ([]string, []string) {
	sourceBound := make([]string, 0, len(families))
	repositoryGlobal := make([]string, 0, len(families))
	for _, family := range families {
		if contracts.RetrievalFamilyRequiresSourceCommit(family) {
			sourceBound = append(sourceBound, family)
			continue
		}
		repositoryGlobal = append(repositoryGlobal, family)
	}
	return sourceBound, repositoryGlobal
}

func normalizeScopePaths(paths []string) []string {
	result := make([]string, 0, len(paths))
	seen := make(map[string]struct{}, len(paths))
	for _, value := range paths {
		value = strings.TrimSuffix(value, "/**")
		if value == "" || value == "**" {
			value = "**"
		}
		if _, exists := seen[value]; !exists {
			seen[value] = struct{}{}
			result = append(result, value)
		}
	}
	sort.Strings(result)
	return result
}

func pathScopes(repositoryPath *string) []string {
	if repositoryPath == nil {
		return []string{"**"}
	}
	clean := path.Clean(*repositoryPath)
	if clean == "." || strings.HasPrefix(clean, "../") || strings.HasPrefix(clean, "/") {
		return []string{"**"}
	}
	result := []string{"**"}
	parts := strings.Split(clean, "/")
	for index := range parts {
		result = append(result, strings.Join(parts[:index+1], "/"))
	}
	return result
}

func pointUUID(pointID string) string {
	digest := sha256.Sum256([]byte("forja-qdrant-point-v1\x00" + pointID))
	bytes := digest[:16]
	bytes[6] = (bytes[6] & 0x0f) | 0x40
	bytes[8] = (bytes[8] & 0x3f) | 0x80
	encoded := hex.EncodeToString(bytes)
	return encoded[0:8] + "-" + encoded[8:12] + "-" + encoded[12:16] + "-" + encoded[16:20] + "-" + encoded[20:32]
}

func float32Values(values []float64) ([]float32, error) {
	converted := make([]float32, len(values))
	for index, value := range values {
		if math.IsNaN(value) || math.IsInf(value, 0) || value > math.MaxFloat32 || value < -math.MaxFloat32 {
			return nil, fmt.Errorf("vector value at index %d cannot be represented as float32", index)
		}
		converted[index] = float32(value)
	}
	return converted, nil
}

func strictAscending(values []uint32) bool {
	for index := 1; index < len(values); index++ {
		if values[index-1] >= values[index] {
			return false
		}
	}
	return true
}

func stringInterfaces(values []string) []any {
	result := make([]any, len(values))
	for index := range values {
		result[index] = values[index]
	}
	return result
}

func loopbackHost(host string) bool {
	if strings.EqualFold(host, "localhost") {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}
